# Generated by Django 5.2.6 on 2025-09-19 07:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TOP', '상의'), ('BOTTOM', '하의'), ('OUTER', '아우터'), ('DRESS', '원피스'), ('SHOES', '신발'), ('BAG', '가방'), ('ACCESSORY', '액세서리')], max_length=20)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=50)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(blank=True, max_length=20)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='clothing_items/')),
                ('tags', models.JSONField(default=list)),
                ('ai_analysis', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothing_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('occasion', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=20)),
                ('weather', models.CharField(blank=True, max_length=50)),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('wear_count', models.IntegerField(default=0)),
                ('last_worn', models.DateTimeField(blank=True, null=True)),
                ('ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('items', models.ManyToManyField(to='wardrobe.clothingitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StylePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_styles', models.JSONField(default=list)),
                ('avoided_styles', models.JSONField(default=list)),
                ('preferred_colors', models.JSONField(default=list)),
                ('avoided_colors', models.JSONField(default=list)),
                ('preferred_brands', models.JSONField(default=list)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('body_type', models.CharField(blank=True, max_length=50)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='style_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
