[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[deploy.environmentVariables]]
name = "DJANGO_SETTINGS_MODULE"
value = "stylemate.settings"

[[deploy.environmentVariables]]
name = "DEBUG"
value = "False"

[[deploy.environmentVariables]]
name = "ALLOWED_HOSTS"
value = "*.railway.app,localhost,127.0.0.1"

[[deploy.environmentVariables]]
name = "DATABASE_URL"
value = "${{Postgres.DATABASE_URL}}"

[[deploy.environmentVariables]]
name = "REDIS_URL"
value = "${{Redis.REDIS_URL}}"

[[deploy.environmentVariables]]
name = "SECRET_KEY"
value = "stylemate-production-secret-key-railway-2024"

[[deploy.environmentVariables]]
name = "CORS_ALLOWED_ORIGINS"
value = "https://stylemate-frontend.vercel.app,http://localhost:3000,http://localhost:3003"

[[deploy.environmentVariables]]
name = "PORT"
value = "8000"
