name: style_mate
description: AI-powered fashion coordination app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_animate: ^4.3.0
  shimmer: ^3.0.0
  
  # State Management
  provider: ^6.1.1
  
  # Network
  dio: ^5.4.0
  retrofit: ^4.0.3
  pretty_dio_logger: ^1.3.1
  
  # Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Image
  image_picker: ^1.0.5
  cached_network_image: ^3.3.1
  image: ^4.1.3
  
  # Camera
  camera: ^0.10.5+7
  
  # Permissions
  permission_handler: ^11.1.0
  
  # Utils
  intl: ^0.18.1
  uuid: ^4.2.2
  path_provider: ^2.1.1
  url_launcher: ^6.2.2
  
  # Location & Weather
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # UI Components
  flutter_slidable: ^3.0.1
  flutter_staggered_grid_view: ^0.7.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  
  # Charts & Analytics
  fl_chart: ^0.65.0
  
  # ML
  tflite_flutter: ^0.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  retrofit_generator: ^8.0.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/fonts/
  
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700